<a href="https://colab.research.google.com/github/Yashsharm20021409/MachineLearning_Complete/blob/main/Python_Lib_numPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

All About Numpy

In [59]:
import numpy as np

List vs Numpy time taken

In [60]:
# used to measure the time
from time import process_time

In [61]:
# for list
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time-start_time)

0.000833109999998527


In [62]:
# for numpy arr
np_array = np.array([i for i in range(10000)])

start_time = process_time()

#np_arr = np_arr + 5
np_array += 5

end_time = process_time()

print(end_time-start_time)

0.00011845999999948731


In [63]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [64]:
#numpy array
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)
# nd = ndimension array
# differnce in both is np array value not seprated by , but list value is see in output

[1 2 3 4 5]


numpy.ndarray

In [65]:
# creating 1-dimension array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [66]:
# shape (dimesnions)
a.shape

(4,)

In [67]:
# multidimensions array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [68]:
b.shape

(2, 4)

In [69]:
# multidimensional array with specfic type data type
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


initial palaceholders

In [70]:
# create a numpy array with all zeroes
# 4,5 = dimensions
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [71]:
# create a numpy array with all ones
# 4,5 = dimensions
y = np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [72]:
# array of particular value
z = np.full((5,4),3)
print(z)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [73]:
# identity matrix
# numbers of row and column should be equal
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [74]:
a.shape

(5, 5)

In [75]:
# np array with random values
b = np.random.random((3,4))
print(b)

[[0.99913272 0.50814548 0.06427195 0.14570231]
 [0.59065656 0.87946302 0.78669768 0.48478287]
 [0.76506011 0.96631434 0.60445503 0.66657685]]


In [76]:
# random integer value with in specific range
# range 10-100
c = np.random.randint(10,100,(3,5))
# c1 = np.random.randint((3,5))
print(c)
# print(c1)

[[83 19 95 77 34]
 [22 55 59 57 44]
 [30 25 22 81 58]]


In [77]:
# array of evenly spaced values
# 10 start pos 30 end 5 is space between values
# specifying number of values
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [78]:
# array of evenly spaced values
# 10 start pos 30 end 5 is space between values
# specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [79]:
# convert a list to numpy
list2 = [1,3,4,5,5]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[1 3 4 5 5]


numpy.ndarray

Analysing a numpy array

In [80]:
c = np.random.randint(10,90,(5,5))
print(c)

[[59 11 52 51 35]
 [43 30 53 23 79]
 [71 89 51 42 60]
 [84 44 78 39 71]
 [25 17 64 37 58]]


In [83]:
# print shape
c.shape

(5, 5)

In [84]:
# print dimension
c.ndim

2

In [85]:
# number of elements in an array
c.size

25

In [87]:
# datatypes of value
print(c.dtype)

int64


Mathematical operations on a np array

In [89]:
list1 = [1,2,3,4,5]
list2 = [5,6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10]


In [90]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [91]:
print(a)
print(b)

[[5 0 4]
 [8 9 4]
 [7 4 1]]
[[19 15 10]
 [18 17 17]
 [16 18 11]]


In [92]:
# one way to perform arithmatic opt on np_arrays
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[24 15 14]
 [26 26 21]
 [23 22 12]]
[[-14 -15  -6]
 [-10  -8 -13]
 [ -9 -14 -10]]
[[ 95   0  40]
 [144 153  68]
 [112  72  11]]
[[0.26315789 0.         0.4       ]
 [0.44444444 0.52941176 0.23529412]
 [0.4375     0.22222222 0.09090909]]


In [93]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [94]:
# other way to perform arithmatic opt
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[19 25 18]
 [20 23 14]
 [20 17 19]]
[[-11  -7 -12]
 [ -2  -9  -6]
 [-10 -15 -11]]
[[ 60 144  45]
 [ 99 112  40]
 [ 75  16  60]]
[[0.26666667 0.5625     0.2       ]
 [0.81818182 0.4375     0.4       ]
 [0.33333333 0.0625     0.26666667]]


Array manipulation

In [96]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 8 8]
 [6 7 6]]
(2, 3)


In [97]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[1 6]
 [8 7]
 [8 6]]
(3, 2)


In [98]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 0 1]
 [4 6 2]]
(2, 3)


In [99]:
# another way to do transpose
trans2 = array.T
print(trans2)
print(trans2.shape)

[[4 4]
 [0 6]
 [1 2]]
(3, 2)


In [100]:
# reshapping of array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[7 5 2]
 [4 3 6]]
(2, 3)


In [107]:
#NOTE:- how it actually works let say array a of size (2,3) = 2*3 = 6 that means after reshaping your array must be of size 6 (make combination is 3*2)
b = a.reshape(3,2)
print(b)
print(b.shape)

[[7 5]
 [2 4]
 [3 6]]
(3, 2)


In [106]:
# c = a.reshape(1,1)
# print(c)
# print(c.shape)